version: "3.9"

services:
  db:
    image: dbaulig/sqlite3
    volumes:
      - ./data/db:/var/lib/sqlite3/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

    depends_on:
      - db