# Generated by Django 4.0.1 on 2022-01-22 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 16, 16, 21, 933036)),
        ),
    ]
